# Generated by Django 5.1.1 on 2024-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apple',
        ),
        migrations.AddField(
            model_name='furniture',
            name='category',
            field=models.CharField(choices=[('home', 'Home Products'), ('office', 'Office Products')], default='home', max_length=10),
            preserve_default=False,
        ),
    ]
